version: '3'
services:
  randomBlog:
    container_name: randomblog # name of our container
    image: randomblog 
    build:
      context: . # where to look for dockerfile
      dockerfile: Dockerfile # filename of dockerfile
    ports:
      - "80:80" # we will be binding port 80 on host to port 80 on our app container
      - "9000:9000" # for webhooks
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_PASSWORD: root # root mysql password
      MYSQL_DATABASE: randomBlog # app database
      MYSQL_USER: alvin # database user
      MYSQL_PASSWORD: alvin123 # database password
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql # database host name to connect to
      PMA_PORT: 3306
    ports:
      - "8899:80" # bind port 8899 on host to 80 on container so we can access phpmyadmin on port 8899 on host
    depends_on:
      - mysql